name: gitupdate-sync
on:
  schedule:
    - cron: '1 */1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-gitupdate-test

  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync gitupdate-test
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/gitupdate/test.git"
          source_branch: "main"
          destination_branch: "gitupdate"
          github_token: ${{ secrets.PAT }}
